# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170113_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
